ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.SerializationKt.configureSerialization
      - com.HttpKt.configureHttp
      - com.MonitoringKt.configureMonitoring
      - com.DatabaseKt.configureDatabases
      - com.SecurityKt.configureSecurity
      - com.StatusPagesKt.configureStatusPages
      - com.RoutingKt.configureRouting

